application: fansbuzzdev
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /script
  static_dir: script
  
- url: /images
  static_dir: images
  
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  
- url: /.*
  script: main.py
